API_url: 'https://.../v3/internal-product' 
apikey: 'apikey' 

DB_host: 'XX.XX.XX.196' 
DB_user: 'login'
DB_port:  port 
DB_password: 'password'
DB_database: 'ntinex' 

# в исходном файле должны присутствоват столбцы с названием 'AccountId', 'GTIN', 'Attributes ID'
input_folder: 'D:/CRPT/2021.08_август/расхождения/combined/concatinated/' 
input_file: 'concatinated8.xlsx'
sheet_name: 'concatinated5'

output_folder: 'D:/CRPT/2021.08_август/расхождения/combined/concatinated/'
output_file: 'concatinated80.xlsx'
